[project]
name = "311-service-request-modelling"
version = "0.1.0"
description = "311 Service Request Modelling"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
]

[project.optional-dependencies]
dev = []

[dependency-groups]
dev = []
